name: GitHub Actions Deploy Dalkong Cam
run-name: ${{ github.actor }} is deploying Dalkong Cam 🚀
on: 
  push:
    branchs:
      - main

jobs:
  Deploy-On-Merge:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Run deploy
        run: |
          echo "Start deploying Dalkong Cam to S3." 
          echo "Running on a ${{ runner.os }} server named ${{ runner.name }}!"
          echo "Branch ${{ github.ref }} from repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install
      - run: firebase -V
      - name: Build project
        run: npm run build
        env:
          CI: ""
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Invalidate
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_S3_DALKONG_CAM_DIST_ID}} --paths "/*" --no-paginate
          echo "Invalidation created"
      - name: Sync files
        run: |
          aws s3 sync --exclude "*.map" --delete ./build s3://dalkong-cam
          echo "Files synced with 's3://dalkong-cam'"
      - name: Deploy finished
        run: echo "Completed ${{ job.status }}."